#!/bin/sh
make
scp index.html kyle@licensezero.com:/var/www/guide.licensezero.com
scp styles.css kyle@licensezero.com:/var/www/guide.licensezero.com
scp *.svg kyle@licensezero.com:/var/www/guide.licensezero.com
